[AT][Guide][Headers][Weather][h1][h2][h4] Verify Guide page headers in Weather body <ElNov686>
RedRoverSchool/OpenWeatherJava_05 pull request #1129
Opened 2022-11-25 22:43 UTC by ElNov686

testVerifyGuidePageHeadersInWeatherbody() added.

[AT] - https://trello.com/c/5ydE3re2

[TC] - https://trello.com/c/fACVk3E2

[US] - https://trello.com/c/iExkTr6C

2022-11-26 01:27 UTC, IrynaKolyada approved these changes

2022-11-26 02:26 UTC, verafes approved these changes

2022-11-26 05:33 UTC, omalanova requested changes
Я уже внесла коррективы в свой тест, на который вы ставите игнор.

2022-11-26 05:33 UTC, omalanova commented on src/test/java/OMalanovaTest.java
> +    @Ignore
Здравствуйте! Я уже исправила свой тест, а вы еще не смерджили этот пиар. почему в вашем пиаре 2 файла?

2022-11-26 09:33 UTC, ElNov686 commented on src/test/java/OMalanovaTest.java
> +    @Ignore
Спасибо, что исправили тест. Я  тогда откачу Ignor. Не смержила, потому что ночь у нас была))

2022-11-26 09:40 UTC, ElNov686 commented on src/test/java/OMalanovaTest.java
> +    @Ignore
Откатила

2022-11-26 17:27 UTC, omalanova commented on src/test/java/OMalanovaTest.java
> +    @Ignore
Отлично, @ElNov686 !

2022-11-26 17:31 UTC, omalanova commented on src/test/java/OMalanovaTest.java
> +    @Ignore
Нет коммита или я не вижу?

2022-11-26 19:25 UTC, ElNov686 commented
@omalanova Вы сделали change requested поэтому я не могу запушить свой тест часов этак 10 уже

2022-11-26 20:03 UTC, verafes commented
@ElNov686, вы можете закрыть это PR и создать новый

2022-11-26 21:11 UTC, ElNov686 commented
> @ElNov686, вы можете закрыть это PR и создать новый

Да, так и сделаю, спасибо за подсказку!

2022-11-26 21:11 UTC, closed without merging

2022-11-27 07:02 UTC, omalanova commented
@ElNov686 Я не снимаю блок, потому что вы не отправляете коммит с откатом игнора. И да, легче сделать новый пиар, чем решать получившийся конфликт