[POM][Structure][TopMenuTest][API] testAPIPageBreadcrumbTitle(), testAPIPageHeader() <Lenochkanik80>
RedRoverSchool/OpenWeatherJava_05 pull request #1218
Opened 2022-11-29 22:43 UTC by lenochkanik80

testAPIPageBreadcrumbTitle(), testAPIPageHeader() tests refactored, 2 tests deleted

[RF] - https://trello.com/c/uGotWKeU/1356-pomstructuretopmenutestapi-testapipagebreadcrumbtitle-testapipageheader-lenochkanik80

2022-11-30 20:55 UTC, kartavenkopavel approved these changes

2022-12-01 04:23 UTC, ArinaJur requested changes

2022-12-01 04:23 UTC, ArinaJur commented on src/test/java/pages/APIPage.java
> +    private WebElement APIPageHeader;
apiPageHeader -  название переменной с маленькой буквы

2022-12-01 04:23 UTC, ArinaJur commented on src/test/java/tests/APITest.java
> +    public void testAPIPageBreadcrumbTitle() {
Ну почему снова Breadcrumb??? :-) Мы просто считываем Title, нигде на странице мы не видим названия Breadcrumb.
Так же Title - это только то название, которое мы видим в коде и которое можем считать методом getDriver().getTitle() Мы Title никогда глазами на странице не видим. 
testAPIPageTitle()

Хотя реально ваш тест на навигацию по кнопке API, те он должен называться testAPIMenuNavigatedToAPIPage(), только на странице TopMenuTest такой тест уже есть, так что поставьте, пожалуйста, ваш ник в конце названия теста

2022-12-01 04:23 UTC, ArinaJur commented on src/test/java/tests/APITest.java
> +    @Test
Этот тест должен быть на странице TopMenuTest

2022-12-01 13:22 UTC, lenochkanik80 commented on src/test/java/pages/APIPage.java
> +    private WebElement APIPageHeader;
Спасибо, Ирина, за Ваш комментарий. Я поменяла название переменой чтобы она начиналась с  маленькой буквы

2022-12-01 13:23 UTC, lenochkanik80 commented on src/test/java/tests/APITest.java
> +    public void testAPIPageBreadcrumbTitle() {
Я удалила это тест (testAPIPageBreadcrumbTitle) чтобы не было повторяющегося теста

2022-12-01 16:37 UTC, ArinaJur approved these changes

2022-12-01 16:38 UTC, merged

2022-12-01 16:38 UTC, ArinaJur commented
Все отлично