[POM][TopMenuPage][TopMenuTest] testCheckUrlTitle_AfterClickOnLogo() <Olga-Khliupina>
RedRoverSchool/OpenWeatherJava_05 pull request #1220
Opened 2022-11-30 00:28 UTC by Olga-Khliupina

testCheckUrlTitle_AfterClickOnLogo() was moved to POM
[POM] - https://trello.com/c/ylHONJE3/1362-pomtopmenupagetopmenutest-testcheckurltitleafterclickonlogo-olga-khliupina

2022-11-30 01:56 UTC, verafes approved these changes

2022-11-30 02:52 UTC, IrynaKolyada approved these changes

2022-12-01 04:28 UTC, ArinaJur requested changes
Придется исправить название соответственно стандарту

2022-12-01 04:28 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public  void testCheckUrlTitle_AfterClickOnLogo() {
testCompanyLogoNavigatesToBaseURL()

2022-12-01 04:33 UTC, Olga-Khliupina commented on src/test/java/tests/TopMenuTest.java
> +    public  void testCheckUrlTitle_AfterClickOnLogo() {
Спасибо, изменила!

2022-12-01 05:53 UTC, ArinaJur approved these changes

2022-12-01 07:04 UTC, merged