[POM][Main][Footer][Widget] testThreeColorTypeWidgetsExists <ElviraKh1>
RedRoverSchool/OpenWeatherJava_05 pull request #1222
Opened 2022-11-30 07:39 UTC by elviraKh1

https://trello.com/c/DBlBYxHR/1366-pom-testthreecolortypewidgetsexists-elvirakh1

2022-11-30 11:51 UTC, SafronovaOlga approved these changes

2022-12-01 05:10 UTC, ArinaJur requested changes

2022-12-01 05:10 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +        List<WebElement> actualRadioBtnsThreeColorsTypeWidgetsList = widgetsPage.listRadioBtnThreeColorsTypeWidgets();
actualWidgetsTypes

2022-12-01 05:10 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +        if (actualRadioBtnsThreeColorsTypeWidgetsList != null) {
Мы никогда не пишем разветвленные сценарии в тестах, те никаких if-else быть не должно.
Если вам нужно подтвердить, что лист считался, то нужно писать 
Assert.assertTrue(actualWidgetsTypes != null)
, но лучше подтверждать
Assert.assertTrue(actualWidgetsTypes.size() > 0)

2022-12-01 05:10 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +            for (WebElement actualRadioBtnThreeColorsTypeWidgets : actualRadioBtnsThreeColorsTypeWidgetsList) {
for(WebElement widgetType : actualWidgetsTypes)

2022-12-01 05:10 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +                        String.format("widget-%s", expectedThreeColorTypeWidgets[i++]));
Проделайте все эти вычисления за пределами ассерта и сохраните результаты в вычисления, а то ассерт совсем не читабельный

2022-12-01 05:10 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +                        widgetsPage.getIdRadioBtnThreeColorsTypeWidgets(actualRadioBtnThreeColorsTypeWidgets),
Разве widgetId не сразу появляется вместе с widget? Зачем мы собираем лист виджетов и потом считываем id, если мы , возможно, сразу можем собирать лист IDs?

2022-12-01 05:12 UTC, elviraKh1 commented on src/test/java/pages/WidgetsPage.java
> +    private WebElement listImgThreeColorsTypeWidgets;
спасибо поменяю

2022-12-01 05:12 UTC, elviraKh1 commented on src/test/java/pages/WidgetsPage.java
> +    private List<WebElement> listRadioBtnThreeColorsTypeWidgets;
спасибо изменю

2022-12-01 05:13 UTC, elviraKh1 commented on src/test/java/tests/WidgetsTest.java
> +        if (actualRadioBtnsThreeColorsTypeWidgetsList != null) {
хорошо

2022-12-01 05:19 UTC, elviraKh1 commented on src/test/java/tests/WidgetsTest.java
> +                        widgetsPage.getIdRadioBtnThreeColorsTypeWidgets(actualRadioBtnThreeColorsTypeWidgets),
возможно я не знаю, что можно сразу собирать id :) , спасибо, переделаю все

2022-12-01 05:55 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +                        widgetsPage.getIdRadioBtnThreeColorsTypeWidgets(actualRadioBtnThreeColorsTypeWidgets),
Наверняка вы сразу в элементе видите его аттрибут, можете сразу считывать аттрибут и собирать значения в List

2022-12-01 06:26 UTC, elviraKh1 commented on src/test/java/tests/WidgetsTest.java
> +                        widgetsPage.getIdRadioBtnThreeColorsTypeWidgets(actualRadioBtnThreeColorsTypeWidgets),
да, что то я сразу не сообразила, спасибо большое за ваши комментарии

2022-12-01 16:36 UTC, elviraKh1 commented on src/test/java/tests/WidgetsTest.java
> +        MainPage mainPage = (MainPage) openBaseURL_ReturnMainPage().scrollToPageBottom();
Можно ли так  в тестах использовать явное приведение к типу?

2022-12-01 16:36 UTC, elviraKh1 commented on src/test/java/pages/BasePage.java
> +    public BasePage scrollToPageBottom() {
можно ли возвращать абстрактный класс ?

2022-12-01 16:52 UTC, ArinaJur requested changes
Добавьте кастомный wrap, пожалуйста, а все остальное отлично!

2022-12-01 16:52 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +    public BasePage scrollToPageBottom() {
Нет. Этот метод должен быть void
А в MainPage нужно создать кастомизированный wrapper:

```
public MainPage scrollToPageBottom() {
    scrollToPageButtom();
    
    return this;
}
```
И тогда в тесте у вас будет возвращаться MainPage, только пролистанная

2022-12-01 16:52 UTC, ArinaJur commented on src/test/java/pages/BasePage.java
> +    public BasePage scrollToPageBottom() {
Но проверьте, по-моему, только что какой-то скролл на MainPage попал в main, так что если он подходит, то переиспользуйте готовый, если нет, напишите свой

2022-12-01 16:52 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +        MainPage mainPage = (MainPage) openBaseURL_ReturnMainPage().scrollToPageBottom();
Использовать можно, в данном случае должен быть кастомный wrapper, я выше написала какой, и тогда все сработает без приведения

2022-12-01 16:52 UTC, ArinaJur commented on src/test/java/tests/WidgetsTest.java
> +    }
Какой хороший и аккуратный тест получился!

2022-12-01 16:57 UTC, elviraKh1 commented on src/test/java/tests/WidgetsTest.java
> +    }
спасибо вам большое, получилось кратко! и простите меня за "Войну и Мир"  и такие большие недоработки, из за которых вы потратили столько своего времени

2022-12-01 16:58 UTC, elviraKh1 commented on src/test/java/pages/BasePage.java
> +    public BasePage scrollToPageBottom() {
Спасибо, я сейчас проверю

2022-12-01 17:19 UTC, elviraKh1 commented on src/test/java/pages/BasePage.java
> +    }
>>Нет. Этот метод должен быть void
>>А в MainPage нужно создать кастомизированный wrapper:
>>
>>public MainPage scrollToPageBottom() {
>>    scrollToPageButtom();
>>    
>>    return this;
>>}
>>И тогда в тесте у вас будет возвращаться MainPage, только пролистанная
оставила BasePage возвращаемый тип иначе не могла наследовать метод, чтоб отдавать MainPage , но изменила модификатор доступа на protected

2022-12-02 02:25 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +
Зачем вы добавили эти элемемнты? Их не было в оригинальном PR. Удалите их, пожалуйста

2022-12-02 02:26 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +}
Этих методов тоже не было в оригинальном PR. На все новые добавления вы должны делать новый PR. Удалите это, пожалуйста, из текущего PR

2022-12-02 02:33 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +
Там 2 новых элемента

2022-12-02 03:21 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +}
извините, я не поняла сразу что это уже закрытый pr,  который не должен редактироваться.

2022-12-02 04:22 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +}
метод был с самого первого коммита и всегда использовался, но почему то в процессе коммитов потерялся из файла на гитхабе
 public WidgetsPage clickOnWidgetsPage() {
        click(widgetsPageLink);

        return new WidgetsPage(getDriver());
 }
    @FindBy(xpath = "//a[@href='/widgets-constructor']")
    private WebElement widgetsPageLink;

2022-12-02 04:55 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +}
Так получилось, что основные изменения с названиями переменных были в коммите [8618095], но потом я заметила, что вы сказали имя метода тоже неправильное и был второй коммит [128e3f8] , где изменилось только имя метода в тесте. В дальнейшем [FooterMenuPage.java] не менялся и в коммиты не подал.

2022-12-02 05:00 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +}
можно мне закрыть pr и сделать новый?

2022-12-02 08:04 UTC, closed without merging