[POM][Main][NavBar][Menu][Support][AskQuestion]testOpenPageAskQuestion_testVerifyHeaderOfForm <TaniaKuno>
RedRoverSchool/OpenWeatherJava_05 pull request #1223
Opened 2022-11-30 07:50 UTC by TaniaKuno

testOpenPageAskQuestion_WhenClickAskQuestionSubmenu() and testVerifyHeaderOfForm_OnAskQuestionPage() refactored with POM

POM https://trello.com/c/W4mZZ06d/1367-pom-test-name-github-username

2022-11-30 09:23 UTC, kartavenkopavel commented on src/test/java/pages/TopMenuPage.java
> +public class TopMenuPage extends BasePage {
Почему Вы решили, что этот класс не должен быть abstract?)

2022-11-30 09:29 UTC, TaniaKuno commented on src/test/java/pages/TopMenuPage.java
> +public class TopMenuPage extends BasePage {
У меня вся строчка подчеркивалась красным, и предлагала класс сделать не абстрактным. Честно, в данном случае я не знаю ничего про абстрактность класса. Если это не неправильно, верну в abstract

2022-11-30 09:47 UTC, kartavenkopavel commented on src/test/java/pages/TopMenuPage.java
> +public class TopMenuPage extends BasePage {
Проблема в методе clickSupportMenu(), вы там пытались создать экзепляр астрактоного класса, т.к. этого делать нельзя интеладжи вам предложила сделать класс обычным) По сути кликая на кнопку Support просто появляется dropdown menu, но вы остаетесь по прежнему на mainpage, думаю можно возвражаеть экземпляр этого класса. Тогда ничего ругаться не будет и в тестах можно будет выстроить цепочку метод, не создавая лишний раз новый экземляр класса. А TopMenuPage нужно сделать abstract )

2022-11-30 09:49 UTC, TaniaKuno commented on src/test/java/pages/TopMenuPage.java
> +public class TopMenuPage extends BasePage {
Поняла, переделаю! Спасибо!

2022-12-01 05:47 UTC, ArinaJur requested changes

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/pages/HomeAskQuestionPage.java
> +    public String getHeaderName() {
headerName - это название элемента в коде, а тут мы просто считываем текст, так что или getHeaderText или getH4Header, тк это просто заголовок 4го уровня, как во всех текстовых редакторах

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +    POMMainNavBarMenuSupportAskQuestion1_TaniaKuno
Наверное решали конфликт и не удалили эту строку. Удалите, иначе код не скомпилируется

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +    private WebElement menuAskQuestion;
этот элемент должен называться askAQuestionSubmenu

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +    private WebElement menuSupport;
supportMenu - смотрите на названия элементов в существующем коде и старайтесь следовать заданному стандарту

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +    public HomeAskQuestionPage clickAskQuestionMenu() {
clickAskAQuestionMenu() - я добавила A тк оно есть в названии

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +    public void testOpenPageAskQuestion_WhenClickAskQuestionSubmenu() {
testAskAQuestionSubmenuNavigatesToHomeAskAQuastionPage()

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +    @Test
Этот тест должен быть на странице TopMenuTest и должен называться 
testAskAQuestionSubmenuNavigatesToHomeAskAQuastionPage()

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +        jumpToNextWindow();
Этот метод мы не используем в POM, для POM есть метод switchToAnotherWindow(), который нужно вызывать от страницы, с которой вы переключаетесь на другое окно

homeAskQuestionPage.switchToAnotherWindow()

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +                .clickAskQuestionMenu();
Вы кликаете на Ask A Question menu, когда все еще находитесь на главной странице, а по вашей схеме получается, что вы кликаете на Ask A Question menu со страницы homeAskQuestionPage. Это неправильно, нужно написать

MainPage mainPage = new MainPage(getDriver())
                .clickSupportMenu()
                .clickAskQuestionMenu();
                
                mainPage.switchToAnotherWindow();
HomeAskQuestionPage homeAskQuestionPage = new HomeAskQuestionPage(getDriver());

String actualURL = homeAskQuestionPage.getCurrentUrl();

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +        String actualURL = getExternalPageURL();
Этот метод для страниц, которые вне нашего POM, но ваша страница все еще в POM, так что посмотрите выше, нужно было от страницы вызывать .getCurrentUrl()

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +    public void testVerifyHeaderOfForm_OnAskQuestionPage() {
Мы не пишем слово Verify в названии автотестов
testAskAQuestionPageHeader()

2022-12-01 05:47 UTC, ArinaJur commented on src/test/java/tests/HomeAskQuestionTest.java
> +                .clickAskQuestionMenu();
Та же ошибка - с неправильной страницы вызываете .clickAskQuestionMenu(); Нужно писать:

MainPage mainPage = new MainPage(getDriver())
.clickSupportMenu()
.clickAskQuestionMenu();

 mainPage.switchToAnotherWindow();
 
HomeAskQuestionPage homeAskQuestionPage = new HomeAskQuestionPage(getDriver());

2022-12-02 08:04 UTC, closed without merging