[POM][Main][NavBar][RFTests] Refactoring tests in POM()<Elena_S>
RedRoverSchool/OpenWeatherJava_05 pull request #1227
Opened 2022-11-30 12:43 UTC by Sosnitsky-E

Refactoring tests in POM()
[POM] -https://trello.com/c/mIOPrEMS/1313-pommainnavbarrftests-refactoring-tests-in-pomelenas

2022-11-30 14:31 UTC, NatalyaYanochkova approved these changes

2022-11-30 14:57 UTC, kartavenkopavel reviewed
Смущает большое количество однотипных методов, которые повторяют один и тоже код. При этом всё сразу проверяется в одном тесте большим количеством Assert. Если есть возможность, лучше сделать один универсальный метод который будет принимать элемент как аргумент. А листом веб элементов собрать все эти элементы и в тесте прогнать лист циклом и одним Assert узнать отражаются элементы или нет. Перед этим можно поставить проверку, что их должно быть определенное количество.

2022-11-30 15:06 UTC, Sosnitsky-E commented
> Смущает большое количество однотипных методов, которые повторяют один и тоже код. При этом всё сразу проверяется в одном тесте большим количеством Assert. Если есть возможность, лучше сделать один универсальный метод который будет принимать элемент как аргумент. А листом веб элементов собрать все эти элементы и в тесте прогнать лист циклом и одним Assert узнать отражаются элементы или нет. Перед этим можно поставить проверку, что их должно быть определенное количество.

этот тест был сделан согласно матрицы покрытия, если есть идеи оптимизации , я только за)

2022-12-01 07:25 UTC, ArinaJur requested changes

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +        return getTitlesMenuElements(mobileMenuElements);
getTitlesMenuElements - title - это название страницы в кодемы title никогда глазами не видим, а считываем методом getTitle()
У вас же считывание названий, текста 
Назовите, пожалуйста getListTexts() 
А публичый метод назовите getHamburgerMenus()

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/pages/TopMenuPage.java
> +
Дубликат

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public void   testVerifyAllElementsOfNavigationBarAreVisibleAndExist(){
Мы не пишем слово Verify в названии автотеста
testAllElementsOnNavigationBarAreDisplayedAndEnable()

Ваших методах не было проверки .isVisible и .isExists
Вы проверяли на .isDisplayed и на isEnabled
 ПОжалуйста пишите в названии ровно то, на что вы тестируете

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    @Test
Поставьте пустую строку

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +        mainPage.clickLogoImage();
Это не проверка на clickable это просто клик.

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public void testLogoExistsAndClickableUserAndStartPageRefresh(){
Тест должен называться 
testLogoIsDisplayedEnabledAndNavigatesToBaseURL()

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    @Test
Добавьте пустую строку

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public void testRedirectToStartPageAfterLogoClick(){
testLogoNavigatesToBaseUrlWhenClickedOnGuidePage()

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +        openURL(guidUrl);
Это в корне неправильная логика. 
Вам нужно
openBaseURL_ReturnMainPage()
.clickGuideMenu
.clickLogoImage();

Assert.assertEquals(mainPage.getCurrentURL(),expectedUrl);

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    @Test
ПУстую строку добавьте, пожалуйста

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public void testHamburgerDisplaysAndEnables(){
testHamburgerMenuDisplayedAndEnabledWhithSertainWindowSize()

2022-12-01 07:25 UTC, ArinaJur commented on src/test/java/tests/TopMenuTest.java
> +    public  void testHamburgerListWithAllElementsNavBarOpens1() {
testHamburgerMenus()

2022-12-01 10:24 UTC, closed without merging