[POM][FooterMenu][Main][WeatherMaps] testAboutUs_testAskAQuestion_testMapOpened_testOpenStreetMap<NataliaRamanenka>
RedRoverSchool/OpenWeatherJava_05 pull request #1251
Opened 2022-11-30 20:35 UTC by NataliaRamanenka

four_tests_in_POM, testAskAQuestionVisibleAndClickable is fixed
[ERR] - https://trello.com/c/KC2crzLe/1337-errnataliaramanenkatesttestaskaquestionvisibleandclickable-ignored
[POM] - https://trello.com/c/smKMjplI/1368-pomfootermenumainweathermaps-testaboutustestaskaquestiontestmapopenedtestopenstreetmapnataliaramanenka

2022-11-30 21:59 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +    @FindBy(xpath = "//div[@class = 'about-us']//h1")
предполагаю,  строки 12-13  headOfAboutUsPage должны находится в классе AboutUsPage   и лучше назвать headerOfAboutUsPage или mainHeaderOfAboutUsPage

2022-12-01 00:37 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +            "//a[@href = 'https://home.openweathermap.org/questions']")
часть xpath   //div[@class = 'footer-section not-foldable']  ненадежна, так как это два класса перечисленных через пробел, которые могут например поменяться местами или туда может добавиться еще один класс ...предлагаю вместо него использовать   //div[@id='footer-website']

2022-12-01 01:51 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement headOfAskAQuestion;
19-20 строки тоже кандидаты для другой страницы HomeAskQuestionPage ?

2022-12-01 09:27 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    @FindBy(xpath = "//div[@class = 'about-us']//h1")
Переместила и переименовала

2022-12-01 09:27 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +            "//a[@href = 'https://home.openweathermap.org/questions']")
исправила

2022-12-01 09:27 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement headOfAskAQuestion;
переместила

2022-12-01 18:23 UTC, elviraKh1 commented on src/test/java/pages/FooterMenuPage.java
> +    @FindBy(xpath = "//div[@class = 'about-us']//h1")
мои и ваши имена переменным сильно избыточны, поэтому тут могут быть проблемы. лучше прочитать пост Ирины про это и посмотреть смерженные pr

2022-12-01 19:06 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    @FindBy(xpath = "//div[@class = 'about-us']//h1")
я переименовала в аboutUsPageHeader, можно сократить до аboutUsHeader? Как считаете?

2022-12-01 23:48 UTC, ArinaJur requested changes
В этом тесте TestSuite ► tests.FooterMenuTest ► testAskAQuestionInFooterMenuDirectToHomeAskQuestionPage_WhenClickOnIt
Failed test found in:
  target/surefire-reports/TEST-TestSuite.xml
Error:
  org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.className: headline' (tried for 10 second(s) with 500 milliseconds interval)
  
  
 плохой локатор.

2022-12-02 03:11 UTC, NataliaRamanenka commented
> В этом тесте TestSuite ► tests.FooterMenuTest ► testAskAQuestionInFooterMenuDirectToHomeAskQuestionPage_WhenClickOnIt Failed test found in: target/surefire-reports/TEST-TestSuite.xml Error: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.className: headline' (tried for 10 second(s) with 500 milliseconds interval)
> 
> плохой локатор.

 изменила на  @FindBy(xpath = "//h4[@class = 'headline']")

2022-12-02 04:56 UTC, ArinaJur requested changes

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement aboutUs;
aboutUsFooterMenu

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement askAQuestion;
askAQuestionFooterMenu - у нас есть похожие элементы в верххнем меню, потому мы договаривались все нижние элементы называть FooterMenu, а верхние Menu

У вас же прямо рядом на строчке 16, 19, 22 есть образцы названий )))

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    public AboutUsPage scrollAndClickOnAboutUs() {
scrollAndClickOnAboutUsFooterMenu()

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    public HomeAskQuestionPage scrollAndClickOnAskQuestion() {
scrollAndClickOnAskQuestionFooterMenu()

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    public AboutUsPage scrollAndClickOnAboutUs() {
Этот метод должен быть на странице MainPage потому тчо вы скроллите MainPage. Вообще, это, наверное, плохая идея объединять эти 2 метода. Тк скроллите вы Main, а кликаете на Footer. В любом случае, Footer - абстрактная страница, обозначающая только маленький контейнер, ее мы не проскроллим

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +        switchToAnotherWindow();
Вы не можете включать switchToAnotherWindow(); в метод, который находится на абстрактной странице, потому что вы переключайтесь с Main на HomeAskQuestionPage. Тоже переносите на main

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/HomeAskQuestionPage.java
> +    public HomeAskQuestionPage askQuestionHeaderIsVisible(){
здесь тоже wait  впереди добавьте, мы ждем, мы не можем утверждать пока

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    private WebElement widgetMap;
mapWidget

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    private WebElement timeContaner;
Это оказалась mapInfo, по-моему, кто-то уже добавлял

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    private WebElement openStreetMap;
openStreetMapCopyright

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    public MainPage scrollToWidgetMap() {
mapWidget - уникальные названия идут первыми

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +    public WeatherMapsPage clickTimeContaner() {
clickMapInfo()

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +        return getCurrentURL();
Ох, все же, это абсолютно неправильно загонять в методы цепочки действий, которые должны быть в тестах. Это тест выполняет действия, чтобы получить результат. А метод - это одно действие, в крайнем случае мы можем что-то переконвертировать, считать элемемнты, а вернуть текст, но мы не выполняем весь тест в одном методе. ПОжалуйста посмотрите на похожие тесты  и методы - в main уже есть образцы, как нужно работать с FooterMenu

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/MainPage.java
> +        return getCurrentURL();
Вот , наприемр, строки 245 - 249 или 251-256 на этой же странице - это как раз одно действие, - проскроллили и вернули страницу, потом на этой же странице делаете второе действие

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/pages/WeatherMapsPage.java
> +    public WeatherMapsPage weatherMapIsVisible(){
wait  в название

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/tests/FooterMenuTest.java
> +    public void testAboutUsInFooterMenuDirectToAboutUsPage_WhenClickOnIt(){
ПОсмотрите, пожалуйста на образец названия на строке 38 и назовите согласно стандарту

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/tests/FooterMenuTest.java
> +    public void testAskAQuestionInFooterMenuDirectToHomeAskQuestionPage_WhenClickOnIt(){
ПОсмотрите, пожалуйста на образец названия на строке 38 и назовите согласно стандарту

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/tests/FooterMenuTest.java
> +    public void testAskAQuestionInFooterMenuDirectToHomeAskQuestionPage_WhenClickOnIt(){
Наши стандарты

Стандарт названия элементов
supportMenu
faqSubmenu
searchField
searchButton
ourTechnologyFooterMenu
листы называйте во множественном числе
supportSubmenus
differentWeatherIcons
То же с тестами
Практически все тесты на страницеTopMenu которые только на что-то кликают и проверяют getURL и getTitle должны называться testНазваниеMenuNavigatesToНазваниеPage
другие тесты называйте по кринципу
testЧтоТестируете   если очень-очень надо, добавляете ГдеТестируете или КогдаЧто-тоОченьСпециальноеДелаете но не запихивайте в название теста полный путь или полный сценарий.

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/tests/MainTest.java
> +    public void testTimeContanerDirectToWeatherMapsPage_WhenClickOnIt(){
Практически все тесты на страницеTopMenu которые только на что-то кликают и проверяют getURL и getTitle должны называться testНазваниеMenuNavigatesToНазваниеPage

2022-12-02 04:56 UTC, ArinaJur commented on src/test/java/tests/MainTest.java
> +    public void testOpenStreetMapLinkInWidgetMapDirectToOpenStreetMapPage_WhenClickOnIt(){
Практически все тесты на страницеTopMenu которые только на что-то кликают и проверяют getURL и getTitle должны называться testНазваниеMenuNavigatesToНазваниеPage

2022-12-02 05:46 UTC, NataliaRamanenka commented on src/test/java/pages/AboutUsPage.java
> +    public AboutUsPage aboutUsPageHeaderIsVisible(){
переименовала в waitForAboutUsPageHeaderBeVisible()

2022-12-02 05:51 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement askAQuestion;
образцы видела, но решала конфликт через гитхаб, и не была уверена, что можно сразу там изменить название, решила что изменю следующую правку через интеледжи, сорри. Переименовала сейчас

2022-12-02 05:51 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    public HomeAskQuestionPage scrollAndClickOnAskQuestion() {
переименовала

2022-12-02 05:53 UTC, NataliaRamanenka commented on src/test/java/tests/FooterMenuTest.java
> +    public void testAboutUsInFooterMenuDirectToAboutUsPage_WhenClickOnIt(){
переименовала в testAboutUsFooterMenuNavigatesToAboutUsPage()

2022-12-02 05:53 UTC, NataliaRamanenka commented on src/test/java/tests/FooterMenuTest.java
> +    public void testAskAQuestionInFooterMenuDirectToHomeAskQuestionPage_WhenClickOnIt(){
переименовала в testAskAQuestionFooterMenuNavigatesToHomeAskQuestionPage()

2022-12-02 05:55 UTC, NataliaRamanenka commented on src/test/java/tests/MainTest.java
> +    public void testTimeContanerDirectToWeatherMapsPage_WhenClickOnIt(){
переименовала в testTimeContanerNavigatesToWeatherMapsPage()

2022-12-02 05:55 UTC, NataliaRamanenka commented on src/test/java/tests/MainTest.java
> +    public void testOpenStreetMapLinkInWidgetMapDirectToOpenStreetMapPage_WhenClickOnIt(){
переименовала в testOpenStreetMapLinkInWidgetMapNavigatesToOpenStreetMapPage()

2022-12-02 06:00 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    private WebElement aboutUs;
переименовала

2022-12-02 06:00 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    public AboutUsPage scrollAndClickOnAboutUs() {
переименовала

2022-12-02 06:00 UTC, NataliaRamanenka commented on src/test/java/pages/FooterMenuPage.java
> +    public HomeAskQuestionPage scrollAndClickOnAskQuestion() {
переименовала

2022-12-02 06:01 UTC, NataliaRamanenka commented on src/test/java/pages/WeatherMapsPage.java
> +    public WeatherMapsPage weatherMapIsVisible(){
добавила

2022-12-02 08:05 UTC, closed without merging