[POM][Main][NavBar][Menu][Maps] testZoomLeafletControl<ElenaHouston>
RedRoverSchool/OpenWeatherJava_05 pull request #1253
Opened 2022-11-30 21:22 UTC by ElenaHouston

Popom main nav bar menu maps test zoom leaflet control elena houston
[POM]-https://trello.com/c/NlAbxuBL/1339-pommainnavbarmenumaps-testzoomleafletcontrolelenahouston

2022-11-30 21:41 UTC, elviraKh1 commented on src/test/java/pages/BasePage.java
> -    }
Получается зря задели BasePage - у вас там нет изменений

2022-11-30 21:41 UTC, elviraKh1 commented on src/test/java/pages/TopMenuPage.java
> +    public String getInnerTextOfPlaceholder(String attribute) {
возможно я не права, но я бы дополнила название метода у какого именно поля мы проверяем placeholder , например так getInnerTextOfPlaceholderOfSearchField

2022-11-30 21:41 UTC, elviraKh1 commented on src/test/java/tests/WeatherMapsTest.java
> +import org.openqa.selenium.WebElement;
тут тоже лишний класс для данного pr

2022-11-30 22:07 UTC, ElenaHouston commented on src/test/java/pages/TopMenuPage.java
> +    public String getInnerTextOfPlaceholder(String attribute) {
Добрый день, это повторный push с решённым конфликтом, название данного метода это работа автора теста, но спасибо за комментарий, я ей передам

2022-11-30 22:08 UTC, ElenaHouston commented on src/test/java/tests/WeatherMapsTest.java
> +import org.openqa.selenium.WebElement;
Это PR с resolved problems, спасибо за комментарий, ветка была смерена вчера

2022-11-30 22:09 UTC, ElenaHouston commented on src/test/java/pages/BasePage.java
> -    }
Спасибо за комментарий, это решение конфликта, ветка была смерена вчера

2022-12-01 00:36 UTC, SergeiKuznetsov commented on src/test/java/tests/WeatherMapsTest.java
> +import org.openqa.selenium.WebElement;
Так отмените правку. Зачем вам добавлять тут импорт?

2022-12-01 00:53 UTC, SergeiKuznetsov requested changes

2022-12-01 00:53 UTC, SergeiKuznetsov commented on src/test/java/tests/WeatherMapsTest.java
> +import org.openqa.selenium.WebElement;
Вот даже инструкцию накидал https://redroverschool.slack.com/archives/C0458UKD3DK/p1669855292890549

2022-12-01 03:14 UTC, ElenaHouston commented on src/test/java/tests/WeatherMapsTest.java
> +import org.openqa.selenium.WebElement;
Спасибо, сейчас поправлю

2022-12-02 03:17 UTC, SergeiKuznetsov approved these changes

2022-12-02 05:00 UTC, ArinaJur approved these changes

2022-12-02 05:00 UTC, merged