[POM][MainPage][MainTest]2 tests moved to POM <Olga-Khliupina>
RedRoverSchool/OpenWeatherJava_05 pull request #1261
Opened 2022-12-01 02:01 UTC by Olga-Khliupina

two tests were moved to POM
[POM] - https://trello.com/c/6A8BSrYA/1379-pommainpagemaintest2-tests-moved-to-pom-olga-khliupina

2022-12-01 12:56 UTC, ViktoriyaED approved these changes

2022-12-02 01:00 UTC, ArinaJur commented on src/test/java/tests/MainTest.java
> +    public void testChangingTempUnitInHeadingToC_WhenSwitchTempUnitButtonToC() {
testTempUnitChangedToC_WhenSwitchingToMetrics() {

2022-12-02 01:03 UTC, ArinaJur commented on src/test/java/tests/MainTest.java
> +    public void testChangingTempUnitInHeadingToF_WhenSwitchTempUnitButtonToF() {
testTempUnitChangedToF_WhenSwitchingToImperial() {

2022-12-02 01:07 UTC, ArinaJur requested changes
Все-таки, попрошу исправить, хоть и очень хочется смержить

2022-12-02 01:35 UTC, Olga-Khliupina commented
> 

Все исправила! Пушнула изменения. Спасибо большое!

2022-12-02 01:42 UTC, ArinaJur approved these changes

2022-12-02 01:42 UTC, merged