[RF][Main][FooterWebsite][Terms&Conditions][PrivacyPolicy]testPrivacyPolicyFooterLinkNavigatesToPrivacyPolicyWeb()<WeraStremedlowska>
RedRoverSchool/OpenWeatherJava_05 pull request #1341
Opened 2022-12-05 16:23 UTC by WeraStremedlowska

testPrivacyPolicyFooterLinkNavigatesToPrivacyPolicyWeb() refactored

[RF] - https://trello.com/c/654t0YRD/1468-rfmainfooterwebsitetermsconditionsprivacypolicytestprivacypolicyfooterlinknavigatestoprivacypolicywebwerastremedlowska

2022-12-05 18:18 UTC, ElNov686 commented on src/test/java/pages/FooterMenuPage.java
> +
У нас в [FooterMenuPage] на 169 строке есть уже универсальный метод который делает switchToAnotherWindow(). Может нам его переименовать в универсальное название и не плодить второй?

2022-12-05 18:25 UTC, WeraStremedlowska commented on src/test/java/pages/FooterMenuPage.java
> +
Спасибо за ваш комментарий, но на 169 строке метод не подходит к моему тесту.
 public void switchToAppStorePage() {
        switchToAnotherWindow();
    } это не универсальный метод, это wrapper

2022-12-05 21:08 UTC, ArinaJur requested changes

2022-12-05 21:08 UTC, ArinaJur commented on src/test/java/pages/FooterMenuPage.java
> +    public void switchToExternalPage() {
Этот метод должен быть в MainPage

2022-12-05 21:13 UTC, WeraStremedlowska commented on src/test/java/pages/FooterMenuPage.java
> +    public void switchToExternalPage() {
я подумала, что мы сначала скроллим до FutterMenu, потом кликаем опять на FutterMenu и по логике подумала переход идет тоже с ФуттерМеню. Наши враппы все и были на FutterMenu

2022-12-06 03:40 UTC, Olga-Khliupina commented on src/test/java/pages/FooterMenuPage.java
> -    public void switchToGithubWebsite() {
Wera, почему вы удаляете методы, которые написали не вы? как мой тест теперь будет работать без этого метода?

2022-12-06 17:48 UTC, Olga-Khliupina commented on src/test/java/pages/FooterMenuPage.java
> -    public void switchToGithubWebsite() {
в этом пиаре  вижу только удаление 2 wrapped methods, которые используются в других тестах. И совсе не вижу создания нового метода, и замену удаляемых методов на новый в тестах. Как тогда существующие тесты будут работать? Если уж исправлять, то надо исправить все, что затрагивается.

2022-12-06 17:55 UTC, Olga-Khliupina commented on src/test/java/pages/FooterMenuPage.java
> +    public void switchToExternalPage() {
в мэйн уже попал тест, где также есть уже wrapped method на переход на сайт Фэйсбук, тогда наверно надо еще будет подтянуть обновления и там тоже поменять...

2022-12-06 17:55 UTC, Olga-Khliupina commented on src/test/java/pages/FooterMenuPage.java
> -    public void switchToGithubWebsite() {
в мэйн уже попал тест, где также есть уже wrapped method на переход на сайт Фэйсбук, тогда наверно надо еще будет подтянуть обновления и там тоже поменять...

2022-12-06 18:43 UTC, WeraStremedlowska commented on src/test/java/pages/FooterMenuPage.java
> -    public void switchToGithubWebsite() {
Да, конечно, этот PR уже устарел, сделаю все заново и посмотрю везде еще раз, чтобы ничего не пропустить

2022-12-06 19:11 UTC, closed without merging