[AT][Functional][Main][NavBar][Menu][Partners]Verify active button 'view on GitHub' and redirection to GitHub from Java hyperlink on Partners and solutions page<ViktoriiaHuk>
RedRoverSchool/OpenWeatherJava_05 pull request #532
Opened 2022-11-14 18:47 UTC by ViktoriiaHuk

testVerifyActiveButtonViewOnGitHubAndRedirectionToGitHubFromJavaHyperlinkOnPartnersPage()

[US] - https://trello.com/c/oTtL1uOO/227-usfunctionalmainnavbarmenupartnerssearch-linksvictoriiahuk
[TC] - https://trello.com/c/vd8nslmH/229-tcfunctionalmainnavbarmenupartnersverify-that-click-on-the-link-java-user-see-the-button-view-on-github-and-click-on-this-button
[AT] - https://trello.com/c/j5kTnYjk/239-atfunctionalmainnavbarmenupartnersverify-active-button-view-on-github-and-redirection-to-github-from-java-hyperlink-on-partners

2022-11-14 18:58 UTC, DimaZadrutsiy approved these changes

2022-11-14 19:25 UTC, ArinaJur requested changes

2022-11-14 19:25 UTC, ArinaJur commented on src/test/java/ViktoriiaHukTest.java
> +            By.xpath("/html/body/main/div[2]/div/div[1]/nav/ul/li[7]/a");
Пожалуйста, не копируйте xPath. Он ненадежен.  Здесь можно использовать By.linkText("Java")

2022-11-14 19:25 UTC, ArinaJur commented on src/test/java/ViktoriiaHukTest.java
>      private static final By DESKTOP_MENU_API = By.xpath("//div[@id = 'desktop-menu']/ul/li[2]/a");
Здесь можно использовать By.linkText("API")

2022-11-14 19:30 UTC, ViktoriiaHuk commented on src/test/java/ViktoriiaHukTest.java
>      private static final By DESKTOP_MENU_API = By.xpath("//div[@id = 'desktop-menu']/ul/li[2]/a");
Спасибо, сейчас исправлю

2022-11-15 00:03 UTC, ArinaJur approved these changes

2022-11-15 05:15 UTC, merged