[AT][Start][Weather][Current Weather][SearchCity]No results Massege
RedRoverSchool/OpenWeatherJava_05 pull request #539
Opened 2022-11-14 21:40 UTC by SafronovaOlga

AT - https://trello.com/c/x6ZqAljz/220-atstartweathercurrent-weathersearchcityno-results-massegesafronovaolga

2022-11-14 21:50 UTC, dmswlpk approved these changes

2022-11-14 21:58 UTC, WeraStremedlowska approved these changes

2022-11-15 00:06 UTC, ArinaJur commented
Пожалуйста, добавьте ваш ник на Гитхаб к названию PR. Лучше копировать полностью название карточки и вставлять это название как название PR

2022-11-15 00:07 UTC, ArinaJur requested changes
Нет имени автора в названии PR

2022-11-15 08:58 UTC, SafronovaOlga reviewed
Я добавила имя в мой ПР. В следующий раз буду внимательней

2022-11-15 11:44 UTC, ArinaJur approved these changes

2022-11-15 11:45 UTC, merged