added testCountColumnOurNewProjects
RedRoverSchool/OpenWeatherJava_05 pull request #615
Opened 2022-11-16 12:42 UTC by ValentinKuprin

[TC] - https://trello.com/c/kbBQxvhR/438-tcmaingridcontainer-verify-countcolumnournewprojects-valentin-kuprin
[AT] - https://trello.com/c/43G8EuEG/439-atmaingridcontainer-verify-countcolumnournewprojects-valentin-kuprin

2022-11-16 13:59 UTC, Sosnitsky-E approved these changes

2022-11-16 20:41 UTC, Olga-Khliupina commented
Поменяйте название вашего пиар, пожалуйста. Название пиар должно быть таким же как и название вашей АТ карточки к этому пиару

2022-11-16 21:03 UTC, ArinaJur requested changes
Поменяйте название PR в соответствии с требованиями, пожалуйста

2022-11-17 04:17 UTC, ValentinKuprin commented
@Olga-Khliupina @ArinaJur 
Спасибо, поправил)

2022-11-17 06:18 UTC, SergeiKuznetsov commented
> А как теперь мердж сделать?)

Подождать, когда Ирина снимет блок.

2022-11-17 15:06 UTC, ArinaJur approved these changes

2022-11-17 19:37 UTC, merged