RfMainNavbarMenuDashboard_testTitleText_whenChooseMenuDashboard_SiarheiMSV
RedRoverSchool/OpenWeatherJava_05 pull request #715
Opened 2022-11-18 01:33 UTC by SiarheiMSV

Choose menu dashboard

2022-11-18 07:08 UTC, DenSebrovsky requested changes
Please change the name of your PR according to requirements

2022-11-18 20:48 UTC, Rom-T commented on src/test/java/SiarheiMSV_Test.java
> +    public void RFMainNavBarMenuDashboard_testTitleText_WhenChooseMenuDashboard_SiarheiMSV (){
метод должен называться с маленькой буквы.

2022-11-19 00:54 UTC, SiarheiMSV commented on src/test/java/SiarheiMSV_Test.java
> +    public void RFMainNavBarMenuDashboard_testTitleText_WhenChooseMenuDashboard_SiarheiMSV (){
Исправил. Спасибо за замечание

2022-11-19 05:21 UTC, DenSebrovsky approved these changes

2022-11-19 06:14 UTC, Rom-T approved these changes

2022-11-19 11:37 UTC, merged