test was deleted
RedRoverSchool/OpenWeatherJava_05 pull request #717
Opened 2022-11-18 01:49 UTC by Dasha1991

[RF] Test was deleted https://trello.com/c/xwdBwJPX/627-rfstartweathercurrentweathertesttemperaturefdeleteddasha1991

2022-11-18 06:52 UTC, AramH20 approved these changes

2022-11-18 07:08 UTC, DenSebrovsky requested changes
Please change the name of your PR according to requirements

2022-11-19 02:07 UTC, Dasha1991 commented
> Please change the name of your PR according to requirements

I ave changed a name.

2022-11-19 05:24 UTC, DenSebrovsky approved these changes

2022-11-19 13:17 UTC, merged