[AT][Main][Start][Weather][DifferentWeatherPopUp] <Timberhut>
RedRoverSchool/OpenWeatherJava_05 pull request #788
Opened 2022-11-19 09:44 UTC by Timberhut

1. [TC] -https://trello.com/c/ihmMlhKf/576-tcmainstartweatherdifferentweatherpopup-timberhut  
2. [AT] - https://trello.com/c/tDTkJICB/579-atmainstartweatherdifferentweatherpopup-timberhut.  
3. [US] - https://trello.com/c/DJj7KDYv/569-usmainstartweatherdifferentweatherpopup-timberhut

2022-11-19 10:43 UTC, omalanova reviewed
На мой взгляд, слишком перегруженный тест.

2022-11-19 10:43 UTC, omalanova commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    public void timbehutMainStartWeatherDifferentWeatherPopUp() {
Тест должен начинаться словом test

2022-11-19 10:43 UTC, omalanova commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    final static String BASE_URL = "https://openweathermap.org/";
Название final переменной из прописных букв, надо и остальные так назвать

2022-11-19 10:43 UTC, omalanova commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    final static String temperature = "26";
Final переменные должны быть прописными буквами

2022-11-19 10:45 UTC, omalanova commented
В названии пиара забыли вставить название теста

2022-11-19 10:52 UTC, Timberhut commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    public void timbehutMainStartWeatherDifferentWeatherPopUp() {
Тест пишется в названии класса)) если бы мой класс не содержал слова Тест, он бы не запустился;)

2022-11-19 10:53 UTC, Timberhut commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    final static String BASE_URL = "https://openweathermap.org/";
про BASE_URL - рекомендую вам пройтись по другим тестам посмотреть

2022-11-19 13:31 UTC, ElNov686 reviewed
Исправьте пожалуйста названия теста - название со слова test

final переменные должны быть заглавными буквами

Это можно сделать этим же PR в своей ветке еще один comment и push

2022-11-19 14:23 UTC, DenSebrovsky commented on src/test/java/TimbehutDifferentWeatherPopUpTest.java
> +    public void timbehutMainStartWeatherDifferentWeatherPopUp() {
Все верно сказано выше. В начале или конце теста обязательно должно быть 'test', Сергей рекомендовал именно в начале писать

2022-11-19 14:38 UTC, ViktoriyaED reviewed
В названии PR и в карточкахTrello отсутствует название теста, над которым вы работаете )

2022-11-20 06:16 UTC, omalanova commented
Смотрю, вы очень упорный! Никак не соглашаетесь с тем, что название PR - неправильное и название теста не содержит слово test!

2022-11-20 06:19 UTC, omalanova requested changes

2022-11-20 06:19 UTC, omalanova commented on src/test/java/TimberhutTest.java
> +    public void timbehutMainStartWeatherDifferentWeatherPopUp() {
Имя теста не по правилам!

2022-11-20 06:25 UTC, IraKalinka commented on src/test/java/TimberhutTest.java
> +    public void timbehutMainStartWeatherDifferentWeatherPopUp() {
название метода должно начинаться с глагола test и не надо в него вписывать свой ник

2022-11-20 15:50 UTC, merged